import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import Tab from '@mui/material/Tab'
import Tabs from '@mui/material/Tabs'

const inter = Inter({ subsets: ['latin'] })

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <p>{children}</p>
      )}
    </div>
  );
}

export default function Home() {
  const [value, setValue] = useState(0)

  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* header with user profile image and info */}
        <header className={styles.header}>
          <div className={styles.header__profile}>
            <Image
              src="/images/profile.jpg"
              alt="profile"
              width={50}
              height={50}
              className={styles.header__profile__image}
            />
            <div className={styles.header__profile__info}>
              <h1 className={styles.header__profile__info__name}>John Doe</h1>
              <p className={styles.header__profile__info__location}>
                New York, NY
              </p>
            </div>
          </div>
        </header>
        {/* main content */}
        <div className={styles.content}>
          {/* tabs */}
          <Tabs
            value={value}
            onChange={handleChange}
          >
            <Tab label="Posts" />
            <Tab label="Info" />
          </Tabs>
          {/* tab panels */}
          <TabPanel value={value} index={0}>
            Posts
          </TabPanel>
          <TabPanel value={value} index={1}>
            Info
          </TabPanel>

        </div>

      </main>
    </>
  )
}
